services:
  - type: worker
    name: studybuddy-ai-bot
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r requirements_bot.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
